# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://Ailuropoda1864.github.io/portfolio
title: Jingfei Cai Portfolio
email: faychoy@gmail.com
author: Jingfei Cai
description: Data science projects and musings by Jingfei Cai
copyright: 'Copyright &copy; 2017 Jingfei Cai. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/Ailuropoda1864
  - title: linkedin
    url: https://linkedin.com/in/jingfei-cai-phd-b06b7548
  - title: 'contact me'
    icon: at
    url: https://docs.google.com/forms/d/e/1FAIpQLSeORqtyVnOE6XKKdiSApBe_hCAolf8a539jcJwBm98uy1fnDA/viewform?usp=sf_link
